- hosts: all
  become: yes
  tasks:
    - name: installing httpd
      yum: name=httpd state=absent
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted


