- hosts: dev
  become: yes
  tasks:
    - name: installing httpd
      yum: name=httpd state=absent
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
    - name: copying the file
      copy:
        src: index.html
        dest: /var/www/html
     
    


